# docker compose file to setup up the environment
# the application uses golang in ./docker/Dockerfile
# and mongodb service

version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:443"
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=organization
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=psps_Ilovecats
    volumes:
      - db-data:/data/db
volumes:
  db-data:
