# docker compose file to setup up the environment
# the application uses golang in ./docker/Dockerfile
# and mongodb service

version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=organization
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=psps_Ilovecats
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=psps_Ilovecats
volumes:
  db-data:
