# docker compose file to setup up the environment
# the application uses golang in ./docker/Dockerfile
# and mongodb service

version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=organization
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=psps_Ilovecats
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=psps_Ilovecats
  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    # instructs the server to save 1 or more writes every 20 seconds to disk in case the server restarts.
    command: redis-server --save 20 1 --loglevel warning --requirepass 8YVvxE9VxmxKPCxmiMtyixVgeoLd2t89
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
