FROM golang:1.21.5-alpine3.17
WORKDIR /app

COPY . .

RUN go build -o main cmd/main.go

EXPOSE 8080

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

# CMD ["/app/main"]
ENTRYPOINT CompileDaemon --build="go build -o main cmd/main.go" --command=./main
